Pass actual android notifications to Linux
FuriLabs/andromeda pull request #3
Opened 2024-11-09 15:09 UTC by farao

notifications_server:
- parse more details about the notifications from the dump, e.g. message hash, title + text (instead of just ticker) and interesting flags
- differentiate between new notification and notification updates
- send removal messages when android notifications disappear (e.g. when messenger messages are read in the android app)

notification_client:
- add notification update and notification removal
- only use urgency 1 when android notification would have triggered the notification led ("show_light"), otherwise 0
- ignore android group banner and background service started notifications for now

2024-11-09 20:26 UTC, FakeShell commented
left some comments. looks pretty good, thanks!
i think squashing the two commits would be a good idea too as one is just pylint and has no significant changes.
most apps seem fine, one app that seems to never give a notification is telegram. i have not investigated much but just by enabling some logging, looks like it gets
Send removal message: 0x0e81d515
when message is opened, but never new message so perhaps a field is missing?

2024-11-09 20:51 UTC, farao commented
Thanks! I don't see the comments yet, did you click on finish review yet? Squashing the commits is fine for me. I unfortunately don't have telegram, would you mind sending me a sample output of `sudo lxc-attach -P /var/lib/waydroid/lxc -n waydroid --clear-env -- /system/bin/sh -c "dumpsys notification --noredact"` when there's a pending telegram notification which should have been shown?

2024-11-09 21:44 UTC, FakeShell commented
right so i did a bit of debugging and here is what i found
on telegram notifications, tickerText is always null
but we can get the actual content from
Bundle[{extras=Bundle[{}], sender_person=android.app.Person@fe4e1284, sender=Test account, text=9000, time=1731188445000}]

this seems to apply for all apps, so for signal i also have:

Bundle[{extras=Bundle[{}], sender_person=android.app.Person@bec9c7ae, sender=Barry, text=Iij, time=1731188243683}]
but for signal, i also get
tickerText=Barry: Iij
which is interesting. some apps leave tickerText empty. perhaps we should check for both? if one is empty just parse Bundle[]?

2024-11-09 21:45 UTC, FakeShell commented
> Thanks! I don't see the comments yet, did you click on finish review yet? Squashing the commits is fine for me. I unfortunately don't have telegram, would you mind sending me a sample output of `sudo lxc-attach -P /var/lib/waydroid/lxc -n waydroid --clear-env -- /system/bin/sh -c "dumpsys notification --noredact"` when there's a pending telegram notification which should have been shown?

yes i can see it in the commits. perhaps something with github? either way, these are the reviews:
![image](https://github.com/user-attachments/assets/c643d0f4-98c9-4d4b-a6db-98816f490bef)

2024-11-09 21:53 UTC, FakeShell requested changes

2024-11-09 21:53 UTC, FakeShell commented on tools/actions/notification_client.py
> +    #logging.info(f"Received new message notification: {msg_hash}, {msg_id}, {package_name}, " +
i think its supposed to be _msg_id instead of msg_id as the signature was changed in the pylint commit

2024-11-09 21:53 UTC, FakeShell commented on tools/actions/notification_client.py
> +    #             f"{show_light}, {when}")
also _when instead of when same as above

2024-11-09 22:27 UTC, farao reviewed
Ah, now the comments are visible. Apparently Github was really slow posting them (they even show after your last message).

Regarding the tickerText: actually my solution reads the tickerText but also (and more importantly) the android.title and android.text fields (which it usually uses to construct the notification, tickerText is just a fallback). Are they missing or empty for telegram?

2024-11-09 22:27 UTC, farao commented on tools/actions/notification_client.py
> +        text = ticker
This is where the decision is made whether title/text are being used or ticker.

2024-11-09 22:41 UTC, FakeShell commented
ah i see
it does have 
                android.title=String (Test account)
                android.text=String (Jjj)
then something else is off somewhere i'm assuming

2024-11-10 02:15 UTC, FakeShell commented
the issue is with the server skipping the iteration when ticker is null. what i think should be done is something like this:
```
            if (n['ticker'] == 'null' or n['ticker'] == '') and (n['title'] == '' or n['text'] == ''):
                logging.error("Ticker is null and title or text are empty. skipping")
                continue
```
so only continue if title or text are empty AND ticker is null. this way we don't move over good messages for no reason

2024-11-10 04:02 UTC, FakeShell commented
i have added some changes here
https://github.com/FuriLabs/waydroid/commits/feature/trixie/notification-improvements/
you can squash both commits and take all authorship
it will fix app opening when notifications are available from multiple apps, fixed telegram and closes all notifications related to one app when its opened. lets say signal has 3 notifications, clicking on open will close all and open the app. thats how android behaves too

2024-11-10 12:56 UTC, farao commented
Thanks for the fixes! I squashed the three commits in one now.

2024-11-10 17:23 UTC, merged